<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<EnableFusionMapperInterceptor>false</EnableFusionMapperInterceptor>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<Optimize>False</Optimize>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="16.2.0" />
		<PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
		<PackageReference Include="Mapster" Version="10.0.11" />
		<PackageReference Include="Riok.Mapperly" Version="4.3.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\FusionMapper\FusionMapper.csproj" />
	</ItemGroup>

	<PropertyGroup>
		<!-- Для preview-режима interceptors, если твой SDK это еще требует -->
		<InterceptorsPreviewNamespaces>$(InterceptorsPreviewNamespaces);FusionMapper.Interceptors</InterceptorsPreviewNamespaces>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\FusionMapper.SourceGenerator\FusionMapper.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>
</Project>
