<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<EnableFusionMapperInterceptor>true</EnableFusionMapperInterceptor>
		<InterceptorsPreviewNamespaces Condition="EnableFusionMapperInterceptor!='false'">$(InterceptorsPreviewNamespaces);FusionMapper.SourceGenerator.Interceptors</InterceptorsPreviewNamespaces>
		<InterceptorsNamespaces  Condition="EnableFusionMapperInterceptor!='false'">$(InterceptorsNamespaces);FusionMapper.SourceGenerator.Interceptors</InterceptorsNamespaces>
	</PropertyGroup>

	<ItemGroup>
		<CompilerVisibleProperty Include="EnableFusionMapperInterceptor" />
	</ItemGroup>	
	
	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="16.2.0" />
		<PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
		<PackageReference Include="Mapster" Version="10.0.11" />
		<PackageReference Include="Riok.Mapperly" Version="4.3.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\FusionMapper\FusionMapper.csproj" />
		<ProjectReference Include="..\..\src\FusionMapper.SourceGenerator\FusionMapper.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>
</Project>
