using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace FusionMapper.SourceGenerator;

class InterceptorGenerator
{
    static readonly string AssemblyName = System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
    static readonly string AssemblyVersion = System.Reflection.Assembly.GetExecutingAssembly().GetName().Version.ToString() ?? "1.0.0.0";

    public static string EmitExpressionCache(
    IEnumerable<Interceptable> candidates)
    {
        var sb = new StringBuilder();

        sb.AppendLine($$"""
            // <auto-generated />
            #nullable enable
                     
            namespace {{AssemblyName}};
           
            static file class ExpressionCacheInitializer
            {
                [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.StaticField, Name = "cache")]
                static extern ref global::System.Collections.Concurrent.ConcurrentDictionary<(global::System.Type Source, global::System.Type Target), global::System.Linq.Expressions.LambdaExpression> GetCache(in global::FusionMapper.ExpressionRewriter c);

                [global::System.Runtime.CompilerServices.ModuleInitializer]
                internal static void Initialize()
                {
                    var cache = GetCache(null!);
            """);

        var types = from c in candidates group c by (c.Source, c.Target) into g select g.Key;
        foreach (var pair in types)
        {
            //sb.AppendLine($$"""
            //        cache.TryAdd((typeof({{pair.Source.Runtime}}), typeof({{pair.Target.Runtime}})),(global::System.Linq.Expressions.Expression<global::System.Func<{{pair.Source.Runtime}},{{pair.Target.Runtime}}>>)({{mapping.ExpressionLambda}}));
            //""");

        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    public static string EmitInterceptors(
        SourceProductionContext spc,
        IEnumerable<Interceptable> candidates,
        AccessorFieldNames accessorFields)
    {
        var sb = GenerateHeader(accessorFields);
        var groups = candidates.GroupBy(c => (c.Source, c.Target, c.Kind, c.Mapping));
        foreach (var group in groups)
        {
            try
            {
                foreach (var candidate in group)
                {
                    AppendInterceptsLocation(sb, candidate.InterceptableLocation);
                }

                var emmittedMapping = MappingEmitter.Emit(group.First());
                GenerateInterceptorMethod(sb, group.Key.Kind, group.Key.Source, group.Key.Target, emmittedMapping);
                sb.AppendLine();
            }
            catch (Exception ex)
            {
                var loc = group.First().Location!;
                spc.ReportDiagnostic(Diagnostic.Create(
                    FusionMapperInterceptorGenerator.IncompatibleMappingRule,
                    loc, group.Skip(1).Select(x => x.Location),
                    group.Key.Source.FullName,
                    group.Key.Target.FullName,
                    ex.Message));
            }
        }

        sb.AppendLine("""
                }
            }
            """);
        sb.AppendLine("#pragma warning restore CS8629");

        return sb.ToString();
    }

    private static StringBuilder GenerateHeader(AccessorFieldNames accessorFields)
    {
        var sb = new StringBuilder($$"""
            // <auto-generated />
            #nullable enable
            #pragma warning disable CS8629

            namespace System.Runtime.CompilerServices
            {
                [global::System.Diagnostics.Conditional("DEBUG")]
                [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
                sealed file class InterceptsLocationAttribute : global::System.Attribute
                {
                    public InterceptsLocationAttribute(int version, string data)
                    {
                        _ = version;
                        _ = data;
                    }
                }
            }
            namespace {{AssemblyName}}.Interceptors
            {
                static file class SourceAccessor<T>
                {
                    [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Field, Name = "{{accessorFields.SourceValueField}}")]
                    public static extern ref T GetValue(in global::FusionMapper.FusionSource<T> t);

                    [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Field, Name = "{{accessorFields.ProjectionValueField}}")]
                    public static extern ref global::System.Linq.IQueryable<T> GetQueryable(in global::FusionMapper.FusionProjection<T> t);
                }

                static file class Interceptors
                {

            """);

        return sb;
    }

    private static void GenerateInterceptorMethod(
        StringBuilder sb,
        CallKind kind,
        TypeModel source,
        TypeModel target,
        IEnumerable<string> emmittedMapping)
    {
        sb.AppendLine($$"""
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{AssemblyName}}", "{{AssemblyVersion}}")]
                    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                    [global::System.Runtime.CompilerServices.MethodImplAttribute(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining | global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveOptimization)] 
            """);
        var methodName = "__" + target.NullableAnnotatedIndentifier;

        if (source.Annotation != NullableAnnotation.NotAnnotated)
            methodName = "Nullable" + methodName;

        switch (kind)
        {
            case CallKind.SourceTo:
                AppendSourceToMethod(sb, source, target, emmittedMapping, methodName);
                break;

            case CallKind.SourceToExisting:
                AppendSourceToExistingMethod(sb, source, target, emmittedMapping, methodName);
                break;

            case CallKind.ProjectionTo:
                AppendProjectionToMethod(sb, source, target, emmittedMapping, methodName);
                break;
        }
    }

    private static void AppendInterceptsLocation(StringBuilder sb, InterceptableLocation location)
    {
        sb.AppendLine($"""
                [global::System.Runtime.CompilerServices.InterceptsLocation({location.Version}, "{location.Data}")]
        """);
    }

    private static void AppendSourceToMethod(
        StringBuilder sb,
        TypeModel source,
        TypeModel target,
        IEnumerable<string> emmittedMapping,
        string methodName)
    {
        var receiver = $"global::FusionMapper.{FusionMapperInterceptorGenerator.FusionSourceType}";

        sb.AppendLine($$"""
                public static {{target.Signature}} Map__{{methodName}}(this in {{receiver}}<{{source.Signature}}> receiver)
                {
        """);

        AppendGetSource(sb, source);
        sb.AppendLine();
        AppendIndented(sb, emmittedMapping, 3);
        sb.AppendLine("""
                }
        """);
    }

    private static void AppendSourceToExistingMethod(
        StringBuilder sb,
        TypeModel source,
        TypeModel target,
        IEnumerable<string> emmittedMapping,
        string methodName)
    {
        var receiver = $"global::FusionMapper.{FusionMapperInterceptorGenerator.FusionSourceType}";

        sb.AppendLine($$"""
                public static {{target.Signature}} Map__{{methodName}}(this in {{receiver}}<{{source.Signature}}> receiver, {{target.Signature}} target)
                {
        """);

        AppendGetSource(sb, source);
        sb.AppendLine();
        AppendIndented(sb, emmittedMapping, 3);
        sb.AppendLine("""
                }
        """);
    }

    private static void AppendProjectionToMethod(
        StringBuilder sb,
        TypeModel source,
        TypeModel target,
        IEnumerable<string> emmittedMapping,
        string methodName)
    {
        var receiver = $"global::FusionMapper.{FusionMapperInterceptorGenerator.FusionProjectionType}";

        sb.AppendLine($$"""
                public static global::System.Linq.IQueryable<{{target.Signature}}> Project__{{methodName}}(this in {{receiver}}<{{source.Signature}}> receiver)
                {
                    ref global::System.Linq.IQueryable<{{source.Signature}}> source = ref SourceAccessor<{{source.Runtime}}>.GetQueryable(in receiver);
                    var rewrittenSource = global::FusionMapper.ExpressionRewriter.Rewrite(source);
        """);
        sb.Append($"            return global::System.Linq.Queryable.Select(rewrittenSource,(");
        sb.Append(emmittedMapping.First());
        foreach(var l in emmittedMapping.Skip(1))
        {
            sb.AppendLine();
            Indent(sb, 4);
            sb.Append(l);
        }
        sb.AppendLine("));");
        sb.AppendLine("""
                }
        """);
    }



    private static void AppendGetSource(StringBuilder sb, TypeModel source)
    {
        if (source.Annotation != NullableAnnotation.NotAnnotated)
        {
            sb.AppendLine("#pragma warning disable CS8620");
        }

        sb.AppendLine($$"""
                    ref {{source.Runtime}} source = ref SourceAccessor<{{source.Runtime}}>.GetValue(in receiver);
        """);

        if (source.Annotation != NullableAnnotation.NotAnnotated)
        {
            sb.AppendLine("#pragma warning restore CS8620");
        }
    }

    private static void AppendIndented(StringBuilder sb, IEnumerable<string> emmittedMapping, int level)
    {
        foreach (var line in emmittedMapping)
        {
            Indent(sb, level);
            sb.AppendLine(line);
        }
    }

    private static void Indent(StringBuilder sb, int level)
    {
        for (int i = 0; i < level * 4; i++)
        {
            sb.Append(' ');
        }
    }
}