<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<WarningsAsErrors>$(WarningsAsErrors);NU1605;Nullable</WarningsAsErrors>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
		<EnableFusionMapperInterceptor>true</EnableFusionMapperInterceptor>
		<InterceptorsPreviewNamespaces Condition="EnableFusionMapperInterceptor!='false'">$(InterceptorsPreviewNamespaces);FusionMapper.SourceGenerator</InterceptorsPreviewNamespaces>
		<InterceptorsNamespaces Condition="EnableFusionMapperInterceptor!='false'">$(InterceptorsNamespaces);FusionMapper.SourceGenerator</InterceptorsNamespaces>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="TUnit" Version="1.*" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\FusionMapper\FusionMapper.csproj" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\FusionMapper.SourceGenerator\FusionMapper.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>

	<ItemGroup>
    	<CompilerVisibleProperty Include="EnableFusionMapperInterceptor" />
  	</ItemGroup>

	<PropertyGroup Condition="'$(EnableFusionMapperInterceptor)' == 'true'">
		<DefineConstants Condition="'$(DefineConstants)' != ''">$(DefineConstants);FUSION_MAPPER_SOURCE_GENERATOR</DefineConstants>
		<DefineConstants Condition="'$(DefineConstants)' == ''">FUSION_MAPPER_SOURCE_GENERATOR</DefineConstants>
	</PropertyGroup>
</Project>
